apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-adp
resources:
  - cluster-full-schedule.yaml
  - critical-ns-hourly-schedule.yaml
  - namespaced-apps-schedule.yaml
