apiVersion: ENC[AES256_GCM,data:wdI=,iv:iB+vMirpC0Wb7az2BR5An2JH+Hm/jBEBwKqjM5htMoY=,tag:VKbyQvH6hCdydgUHaH5QNw==,type:str]
kind: ENC[AES256_GCM,data:j8FW4yxN,iv:E3GzDUhYKgdH8UfurmAvnZLC0vg/9FECH1V9wlqrsWQ=,tag:6p+gHPFAb9CAR0mzM6QZfg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jWbhsxM7jUFEWBfQ6xfB3t4=,iv:XluaNOPaOezIA72MtNyje2Oslb8QZMAJZmwW2OOk+Qo=,tag:J7mE3YPjc6BabrFBLlegKQ==,type:str]
    namespace: ENC[AES256_GCM,data:IO+Q5iqF/0NHKMtR9w==,iv:wWCnjrZRmj80iuYywQb9JHaHeBNikPE0mlU3cnXHakU=,tag:AwOzoc/kxp27z+eB+sNlKA==,type:str]
type: ENC[AES256_GCM,data:qF/ATQt0,iv:StR1CRe6GdiPQ3syBcjhw9PwQGa258vDQfxKdO4GMbE=,tag:onJbCypTuaE4dNdzMtsIBA==,type:str]
stringData:
    cloud: ENC[AES256_GCM,data:zHo7jR99pYePbpDhQYZ+2Nq+znfA6DcHKKcaWmAcDPdThgmRXaCE77b3tV7vxpjAUjoZ/EyQUbB+c4wwIz7CTZSLSAZvH2T1gQ==,iv:xAFn2Tb3wEY/U0uxYaKL9jnM1YSXlc3qTvgv9q2gwss=,tag:/gnNpfxaIPzhdmxfCra+xA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wydmjgnuq8drnjll2nv74cn28t5yhrremazhp6ecthrh70wl3avs6dvre3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bkVnUm5nQW9yVmVwR096
            R1hINXdhbTg0YXpYZlJVVllyUllJdnZEK3k4Ci9ONStBZmptRFdTMXZLb0srWnVi
            SkxkcTMyaWFBRldqMXdXb2cvc0kwVXMKLS0tIHZJN3RUT01DaGxBRnk0UjhqeUky
            L1E4aDJxVFhtZVQrcGlPYmYzaUhhK3cKwLcGBxUw2IaiZDQznk2057ND3i4FvFx5
            XSni4zI/5bb3Ken9wk5lDJmG0UfH89PpNSSnOdPqfEf/ppcFWI4S/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T17:22:45Z"
    mac: ENC[AES256_GCM,data:CcSOYvYm/uesd1fVPbdUxlwR5maz5fa5VgbPs0UqWd97E/TgoxHMZ5opMm6iAWVymTH3iMVHwofN13pmj/0xWvS766ZxLX2TI1LJSAxR2jrTCjJEgcPovNZNO8e0mbJsQpBeGizLeA9p4yO7Fyy/UJn8sOcuCjuOnLUlGwFFv3g=,iv:1D1vZZ6xR0IB+BQ0Tsopg3lnU/mBrsYnxZWwhNz0Lcw=,tag:zHoGsRpufhfJeuJkPy+wZA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
