apiVersion: ENC[AES256_GCM,data:6FQ=,iv:GpVFdMSRe9DzABuCw38LSRVo4FYzHSG8O6s11u9bE/Y=,tag:Jqq/ckt0Ffwx3Irc5uL6Qg==,type:str]
kind: ENC[AES256_GCM,data:U71I62yD,iv:ZkiDtOcuudrVuINQ+nXMMjWi8YF84TLpXGge+5JPcII=,tag:BAfMPvI781rOlYJHZx6jxw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5V4mi87ZXI/+6dsB4Lc=,iv:wkXQEtAoIuyHsyjPDPhpj/2BsXIerl5FdfTy6cbk53M=,tag:Bi4rEri0K6JeeVM7UHog2w==,type:str]
type: ENC[AES256_GCM,data:7wfZdFHh,iv:a/hs1zdmCwTOHIu6TEyXgx5Hfx/bWD9r2j84L+akdcQ=,tag:rxtU4/fpkU1Sqa3i/qpZwg==,type:str]
stringData:
    aws_access_key_id: ENC[AES256_GCM,data:lRrmpy6R,iv:1+PzwmEy+LKqEEHUSjs6rm/rqGAjSDcViV/ftBoVfYI=,tag:3zv3CB8s7EuTtweUYmwxyA==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:GT13g8E1,iv:rhHvnKrYdO8kefKMB0K7TDOFQ7lvf1ngMaBz5ht5sqs=,tag:ZlVV4vkFMKFJ7p5w1Imy4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ducwp7j53xn4em9qfft09pn59ewv4gspmj4p3m8v66rnzld4qdsgfr8sk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSWJneC9PZExlM21MaDBJ
            ZHBLZlVSN3Z6US9JS1dtdVlIVVZHZG4veXlBCkFxdjZJRXl0c1hlU1VuREttcGx3
            WE5KOUFNSXpJY3V2cXNlMEllaCswTTQKLS0tIDc5bjdneS96QTFYSGxKaVVEd1pr
            R0Q4ZEJnVVBBZ0h2enRBVnRhcDdZL0UK+iwnK2eHnPnmWnddJNKbdYrzRlq66MpO
            EYbj9t1Q+0FmWlNZF0fn7TO/4JFnD0hgmHTTuo5AeN/G5Daex8RJKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T17:43:50Z"
    mac: ENC[AES256_GCM,data:In63B5M1rxUNmKBXwetJGlMtYhE3uWzsajeDluu4s98t6Yz2k9CLBDpeQ+csPB7ExEezv1Q30OsK+qDD2RJOYbYgLpAHjAtcM2fc4y5GlSKJYMMgRWqpVpmYsqJ4NrurEaw2DbGScrw5GdeUBUrMyDmBu30tV/2DILUefqBZWvU=,iv:JFYoQ4poqYzSMHdhpFnyW0WHCLYO94DqsBaT1SKco3w=,tag:wpSBWDxnSETOvTOObhHNYw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
