apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: backup
type: Opaque
stringData:
  aws_access_key_id: YOUR_KEY
  aws_secret_access_key: YOUR_SECRET
  aws_bucket: YOUR_BUCKET
  aws_region: YOUR_REGION
