apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vso
  namespace: flux-system
spec:
  interval: 10m
  path: ./vault-secrets/vso
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: vault
