apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mysql-credentials
  namespace: mis-restore
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: mis/mysql
  refreshAfter: 30s
  destination:
    name: mysql-vault-secret
    create: true
    labels:
      managed-by: vault-secrets-operator
    transformation:
      excludeRaw: true
      templates:
        MYSQL_ROOT_PASSWORD:
          text: "{{ .Secrets.root_password }}"
        MYSQL_USER:
          text: "{{ .Secrets.user }}"
        MYSQL_PASSWORD:
          text: "{{ .Secrets.password }}"
        MYSQL_DATABASE:
          text: "{{ .Secrets.database }}"
