apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - vaultconnection.yaml
  - vaultauth.yaml
  - minio-creds-sync.yaml
  - minio-env-sync.yaml
patches:
  - path: storage-patch.yaml
