apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: openshift-adp
  labels:
    app.kubernetes.io/managed-by: flux
spec:
  provider: aws
  default: true
  objectStorage:
    bucket: openshift-backups
    prefix: ocp-production
  config:
    region: us-east-1
    s3Url: https://minio.yourdomain.com
    insecureSkipTLSVerify: 'false'
  credential:
    name: cloud-credentials
    key: cloud
