apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: openshift-adp
spec:
  provider: aws
  default: true
  objectStorage:
    bucket: openshift-backups
    prefix: ocp-production
  config:
    region: us-east-1
    s3Url: http://minio.openshift-adp.svc:9000
    insecureSkipTLSVerify: "true"
    s3ForcePathStyle: "true"
  credential:
    name: cloud-credentials
    key: cloud
