apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This prevents Kustomize from generating implicit namespaces
namespace: openshift-adp

resources:
  - ./secrets/
  - ./oadp/
  - ./velero/
  - ./etcd/
