apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secrets/
  - ./oadp/dpa.yaml
  - ./oadp/operatorgroup.yaml
  - ./oadp/subscription.yaml
  - ./velero/bsl.yaml
  - ./velero/schedules/cluster-full-schedule.yaml
  - ./velero/schedules/critical-ns-hourly-schedule.yaml
  - ./velero/schedules/namespaced-apps-schedule.yaml
  - ./etcd/sa.yaml
  - ./etcd/rbac.yaml
  - ./etcd/cronjob.yaml