apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../clusters/production/backup-platform/namespace.yaml
  - ../../../clusters/production/backup-platform/minio
  - ../../../clusters/production/backup-platform/secrets
  - ../../../clusters/production/backup-platform/oadp/dpa.yaml
  - ../../../clusters/production/backup-platform/velero
