apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: dpa
  namespace: openshift-adp
spec:
  backupLocations:
    - velero:
        provider: aws
        default: true
        objectStorage:
          bucket: openshift-backups
          prefix: ocp-production
        config:
          region: us-east-1
          s3Url: https://minio.yourdomain.com
          insecureSkipTLSVerify: "false"
        credential:
          name: cloud-credentials
          key: cloud
  configuration:
    velero:
      defaultPlugins:
        - openshift
        - aws
        - csi
